import { DocumentNode } from 'graphql';
import {
  addMessageMutation,
  addMessageMutationVariables,
  addMessage as addMessageDoc,
  myChats as myChatsDoc,
  myChatsQueryVariables,
  myChatsQuery,
  getChat as getChatDoc,
  getChatQueryVariables,
  getChatQuery,
} from './generated/graphql';

// NOTE: entire content of this file should be autogenerated via some tooling
// important part is to capture input/output types and a query/mutation object that will carry the types
// basically similar to apollo react hooks codegen but as a data structure

export type Operation<I, O> = {
  input: I;
  output: O;
  node: DocumentNode;
};

const defineOperation = <I, O>(node: DocumentNode): Operation<I, O> =>
  ({ node } as any);

export const addMessage = defineOperation<
  addMessageMutationVariables,
  addMessageMutation['postMessage']
>(addMessageDoc);

export const myChats = defineOperation<
  myChatsQueryVariables,
  myChatsQuery['myChats']
>(myChatsDoc);

export const getChat = defineOperation<
  getChatQueryVariables,
  getChatQuery['chat']
>(getChatDoc);
